#!/usr/bin/env python3
"""Generate INDEX.md (global) and TOC.md (per-document).

Reads every docs/<slug>/document.md and produces:
- docs/<slug>/TOC.md — header outline with line anchors
- INDEX.md — global table, abstracts, top-level sections, optional
  feature-map (loaded from feature-map.json if present)

Pure regex/JSON, no LLM. Output is deterministic — re-running with no
input changes produces identical bytes.
"""
from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(os.environ.get("DOCLENS_ROOT", ".")).resolve()
DOCS = ROOT / "docs"
SLUGS_FILE = ROOT / "slugs.json"
FEATURE_MAP_FILE = ROOT / "feature-map.json"

HEADER_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")


def read_meta(slug_dir: Path) -> dict:
    p = slug_dir / "meta.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def extract_headers(md_path: Path) -> list[tuple[int, int, str]]:
    if not md_path.exists():
        return []
    return [
        (lineno, len(m.group(1)), m.group(2).strip())
        for lineno, line in enumerate(md_path.read_text(encoding="utf-8").splitlines(), start=1)
        if (m := HEADER_RE.match(line))
    ]


def document_title(headers: list[tuple[int, int, str]]) -> str:
    """First H1 in first 50 lines, else first header in first 50 lines, else first header."""
    early = [(ln, lvl, t) for ln, lvl, t in headers if ln <= 50]
    for _, lvl, t in early:
        if lvl == 1:
            return t
    if early:
        return early[0][2]
    return headers[0][2] if headers else "(untitled)"


def extract_abstract(md_path: Path, headers: list[tuple[int, int, str]]) -> str:
    if not md_path.exists() or not headers:
        return ""
    lines = md_path.read_text(encoding="utf-8").splitlines()
    start = 0
    for lineno, _, _ in headers:
        if lineno <= 50:
            start = lineno
            break
    paragraph: list[str] = []
    for line in lines[start:start + 40]:
        s = line.strip()
        if not s:
            if paragraph:
                break
            continue
        if s.startswith(("#", "<!--", "![", "|", "-", "*")):
            if paragraph:
                break
            continue
        paragraph.append(s)
        if len(" ".join(paragraph)) > 400:
            break
    text = " ".join(paragraph)
    sentences = re.split(r"(?<=[.!?])\s+", text)
    return " ".join(sentences[:3]).strip()


def write_toc(slug_dir: Path, headers: list[tuple[int, int, str]]) -> None:
    toc_path = slug_dir / "TOC.md"
    if not headers:
        if toc_path.exists():
            toc_path.unlink()
        return
    lines = [
        f"# Table of Contents — {slug_dir.name}",
        "",
        "Generated by `build_index.py` — do not edit manually.",
        "",
    ]
    for lineno, level, text in headers:
        indent = "  " * (level - 1)
        lines.append(f"{indent}- [{text}](document.md#L{lineno})")
    lines.append("")
    toc_path.write_text("\n".join(lines), encoding="utf-8")


def build_entry(slug: str, slug_dir: Path) -> dict:
    meta = read_meta(slug_dir)
    doc = slug_dir / "document.md"
    headers = extract_headers(doc)
    return {
        "slug": slug,
        "title": document_title(headers),
        "pages": meta.get("page_count") or "–",
        "source": meta.get("source_pdf", "–"),
        "abstract": extract_abstract(doc, headers) or "(no abstract)",
        "headers": headers,
    }


def load_slug_order() -> list[str]:
    if not SLUGS_FILE.exists():
        return []
    raw = json.loads(SLUGS_FILE.read_text(encoding="utf-8"))
    return raw.get("_order", []) if isinstance(raw, dict) else []


def load_feature_map() -> list[dict]:
    if not FEATURE_MAP_FILE.exists():
        return []
    raw = json.loads(FEATURE_MAP_FILE.read_text(encoding="utf-8"))
    if isinstance(raw, list):
        return raw
    return []


def render_index(entries: list[dict], feature_map: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = [
        "# Knowledge Base — Index",
        "",
        f"Generated: {now} by `scripts/build_index.py` — do not edit manually.",
        "",
        "Entry point for AI agents and humans. See [CLAUDE.md](CLAUDE.md) (or AGENTS.md) for navigation rules.",
        "",
        "## Documents",
        "",
        "| Slug | Title | Pages | Source |",
        "|---|---|---:|---|",
    ]
    for e in entries:
        lines.append(
            f"| [`{e['slug']}`](docs/{e['slug']}/) | {e['title']} | {e['pages']} | `{e['source']}` |"
        )
    lines.append("")
    lines.append("## Abstracts")
    lines.append("")
    for e in entries:
        lines.append(f"### {e['title']} (`{e['slug']}`)")
        lines.append("")
        lines.append(e["abstract"])
        lines.append("")
        lines.append(f"→ [TOC](docs/{e['slug']}/TOC.md) · [document.md](docs/{e['slug']}/document.md)")
        lines.append("")

    lines.append("## Top-level sections per document")
    lines.append("")
    for e in entries:
        lines.append(f"### `{e['slug']}`")
        lines.append("")
        top = [h for h in e["headers"] if h[1] <= 2]
        if not top:
            lines.append("_(no headers detected)_")
        else:
            for ln, lvl, t in top[:30]:
                prefix = "-" if lvl == 1 else "  -"
                lines.append(f"{prefix} [{t}](docs/{e['slug']}/document.md#L{ln})")
        lines.append("")

    if feature_map:
        lines.append("## Feature → document map")
        lines.append("")
        cols = ["Feature"] + [c for c in (feature_map[0].get("_columns") or []) if c]
        if not any("_columns" in row for row in feature_map):
            cols = ["Feature", "Primary", "Secondary"]
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("|" + "|".join(["---"] * len(cols)) + "|")
        for row in feature_map:
            if "_columns" in row:
                continue
            cells = [row.get("feature", "")]
            for col in cols[1:]:
                v = row.get(col.lower(), row.get(col, "—"))
                if v != "—" and v:
                    cells.append(f"[`{v}`](docs/{v}/)")
                else:
                    cells.append("—")
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not DOCS.exists():
        print(f"ERROR: {DOCS} does not exist. Run convert.py first.", file=sys.stderr)
        return 1

    found = {d.name: d for d in DOCS.iterdir() if d.is_dir()}
    order = load_slug_order()
    ordered = [s for s in order if s in found]
    extra = sorted(s for s in found if s not in ordered)
    all_slugs = ordered + extra
    if not all_slugs:
        print("No slug directories found.", file=sys.stderr)
        return 1

    entries: list[dict] = []
    skipped: list[str] = []
    for slug in all_slugs:
        d = found[slug]
        if not (d / "document.md").exists():
            skipped.append(slug)
            continue
        entry = build_entry(slug, d)
        entries.append(entry)
        write_toc(d, entry["headers"])
    if skipped:
        print(f"Note: skipped {len(skipped)} slug(s) without document.md: {skipped}")

    feature_map = load_feature_map()
    (ROOT / "INDEX.md").write_text(render_index(entries, feature_map), encoding="utf-8")
    print(f"INDEX.md written ({len(entries)} document(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
